"""
Base strategy interface and signal definitions.
All strategies implement the same interface for composability.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal, Optional

import pandas as pd


@dataclass
class TradeSignal:
    """A trade signal generated by a strategy."""
    symbol: str
    action: Literal["BUY", "SELL", "SHORT", "COVER", "HOLD", "PASS"]
    strength: float             # 0.0 to 1.0
    strategy_name: str
    entry_price: float = 0.0
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.10
    holding_period_days: int = 10
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.now)

    @property
    def is_actionable(self) -> bool:
        return self.action in ("BUY", "SELL", "SHORT", "COVER") and self.strength >= 0.6


class Strategy(ABC):
    """Base class for all trading strategies."""

    name: str = "base"

    @abstractmethod
    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        current_position: Optional[dict] = None,
    ) -> TradeSignal:
        """Generate a trade signal for a single symbol."""
        ...

    @abstractmethod
    def is_suitable_regime(self, regime: str) -> bool:
        """Check if this strategy should be active in the current market regime."""
        ...
